=== perlovdinger/gloria1/Gloria/GloriaUtil/src/main/resources/xsd/materialrequest/MaterialProcureRequest.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.volvo.com/MaterialProcureRequest/1_0" xmlns:volvo="http://www.volvo.com/group/common/1_0" targetNamespace="http://www.volvo.com/MaterialProcureRequest/1_0" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0.0">
	<xsd:import namespace="http://www.volvo.com/group/common/1_0" schemaLocation="VolvoCommon_1_0.xsd"/>
	<xsd:element name="ProcessMaterialProcureRequest" type="ProcessMaterialProcureRequestType"/>
	<!-- Start of Complex Types -->
	<xsd:complexType name="ProcessMaterialProcureRequestType">
		<xsd:complexContent>
			<xsd:extension base="volvo:BODType">
				<xsd:sequence>
					<xsd:element name="DataArea">
						<xsd:complexType>
							<xsd:sequence>
								<xsd:element name="Process" type="volvo:ProcessType"/>
								<xsd:element name="MaterialRequestChange" type="MaterialRequestChangeType" maxOccurs="unbounded"/>
							</xsd:sequence>
						</xsd:complexType>
					</xsd:element>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:complexType name="MaterialRequestChangeType">
		<xsd:sequence>
			<!--<xsd:element name="RequestType" type="RequestType" maxOccurs="1"/>-->
			<xsd:element name="RequestType" type="xsd:string" maxOccurs="1"/>
			<xsd:element name="MaterialRequestChangeAdd" type="MaterialRequestChangeTypeAdd" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="MaterialRequestChangeRemove" type="MaterialRequestChangeTypeRemove" minOccurs="0" maxOccurs="1"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="MaterialRequestChangeTypeAdd">
		<xsd:sequence>
			<xsd:element name="Id" type="xsd:string" minOccurs="0"/>
			<xsd:element name="Type" type="xsd:string" minOccurs="1"/>
			<xsd:element name="ChangeTechId" type="xsd:string"/>
			<xsd:element name="MtrlRequestVersion" type="xsd:string" minOccurs="0"/>
			<xsd:element name="ProcureMessageId" type="xsd:string" minOccurs="0"/>
			<xsd:element name="Title" type="xsd:string" minOccurs="0"/>
			<xsd:element name="ProcurePrioritity" type="xsd:string" minOccurs="0"/>
			<xsd:element name="ApprovalInfo" type="ApprovalInfoType" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="MaterialRequestMessage" type="MaterialRequestMessageType" minOccurs="1" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="MaterialRequestChangeTypeRemove">
		<xsd:sequence>
			<xsd:element name="ChangeTechId" type="xsd:string" minOccurs="1" maxOccurs="1"/>
			<xsd:element name="MtrlRequestVersion" type="xsd:string" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="ApprovalInfoType">
		<xsd:sequence>
			<xsd:element name="MailformId" type="xsd:string"/>
			<xsd:element name="ApprovalAmount" type="xsd:double" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="ApprovalCurrency" type="xsd:string" minOccurs="0" maxOccurs="1"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="MaterialRequestMessageType">
		<xsd:sequence>
			<xsd:element name="Header" type="HeaderType" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="Component" type="ComponentType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="HeaderType">
		<xsd:sequence>
			<xsd:element name="MaterialRequestHeader" type="MaterialRequestHeaderType" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="TestObjectHeader" type="TestObjectHeaderType" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="AdditonalUsageHeader" type="AdditonalUsageHeaderType" minOccurs="0" maxOccurs="1"/>						
			<xsd:element name="Requester" type="RequesterType" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="ContactPerson" type="ContactPersonType" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="MaterialController" type="MaterialControllerType" minOccurs="0" maxOccurs="1"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="MaterialRequestHeaderType">
		<xsd:sequence>
			<xsd:element name="ReferenceId" type="xsd:string" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="ReferenceGroup" type="xsd:string" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="OutboundLocationId" type="xsd:string" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="OutboundStartDate" type="xsd:date" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="RequiredShipToArrive" type="xsd:date" minOccurs="0" maxOccurs="1"/>            
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="TestObjectHeaderType">
		<xsd:sequence>
			<xsd:element name="TestObjectInfo" type="TestObjectInfoType" maxOccurs="1"/>
			<xsd:element name="PhaseInfo" type="PhaseType" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="BuildSeriesInfo" type="BuildSeriesType" minOccurs="0" maxOccurs="1"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="AdditonalUsageHeaderType">
		
	</xsd:complexType>
	<xsd:complexType name="TestObjectInfoType">
		<xsd:sequence>
			<xsd:element name="TestObjectRemove" type="TestObjectRemoveType" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="TestObject" type="TestObjectType" minOccurs="1" maxOccurs="1"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="TestObjectRemoveType">
		<xsd:sequence>
			<xsd:element name="Id" type="xsd:string" minOccurs="0" maxOccurs="1"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="TestObjectType">
		<xsd:sequence>
			<xsd:element name="Id" type="xsd:string"/>
			<xsd:element name="Type" type="xsd:string"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="PhaseType">
		<xsd:sequence>
			<xsd:element name="PhaseRemove" type="PhaseRemoveType" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="Phase" type="PhaseAddType" minOccurs="0" maxOccurs="1"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="PhaseRemoveType">
		<xsd:sequence>
			<xsd:element name="Id" type="xsd:string" minOccurs="0" maxOccurs="1"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="PhaseAddType">
		<xsd:annotation>
			<xsd:documentation>A Phase represents a Build of a TestObject at a specific buildlocation
       Phase type can be REFERENCE/FIRST_ASSEMBLY/REBUILD</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="Id" type="xsd:int"/>
			<xsd:element name="Name" type="xsd:string"/>
			<xsd:element name="Type" type="xsd:string"/>
			<xsd:element name="PlannedAssemblyStartDate" type="xsd:date"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="BuildSiteType">
		<xsd:sequence>
			<xsd:element name="Id" type="xsd:string"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="BuildSeriesType">
		<xsd:sequence>
			<xsd:element name="BuildSeriesRemove" type="BuildSeriesRemoveType" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="BuildSeries" type="BuildSeriesAddType" minOccurs="0" maxOccurs="1"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="BuildSeriesRemoveType">
		<xsd:sequence>
			<xsd:element name="Id" type="xsd:string" minOccurs="0" maxOccurs="1"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="BuildSeriesAddType">
		<xsd:annotation>
			<xsd:documentation>Build Series of TestObject</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="Id" type="xsd:string"/>
			<xsd:element name="Name" type="xsd:string"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="FinancialInfoType">
		<xsd:sequence>
			<xsd:element name="ProjectId" type="xsd:string" minOccurs="0"/>
			<xsd:element name="CompanyCode" type="xsd:string" minOccurs="0"/>
			<xsd:element name="GlAccount" type="xsd:string" minOccurs="0"/>
			<xsd:element name="CostCenter" type="xsd:string" minOccurs="0"/>
			<xsd:element name="WbsCode" type="xsd:string" minOccurs="0"/>
			<xsd:element name="InternalOrderNoSAP" type="xsd:string" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="RequesterType">
		<xsd:annotation>
			<xsd:documentation>Requester of the MaterialRequestMessage</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="UserId" type="xsd:string"/>
			<xsd:element name="Name" type="xsd:string" minOccurs="0"/>
			<xsd:element name="Notes" type="xsd:string" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="ContactPersonType">
		<xsd:annotation>
			<xsd:documentation>Contact person of the procure request</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="UserId" type="xsd:string" minOccurs="0"/>
			<xsd:element name="Name" type="xsd:string" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>
    <xsd:complexType name="MaterialControllerType">
      <xsd:annotation>
        <xsd:documentation>Materia Controller assigned to procure request</xsd:documentation>
      </xsd:annotation>
      <xsd:sequence>
        <xsd:element name="UserId" type="xsd:string" minOccurs="0"/>
        <xsd:element name="Name" type="xsd:string" minOccurs="0"/>
      </xsd:sequence>
    </xsd:complexType>
	<xsd:complexType name="ComponentType">
		<xsd:sequence>
			<xsd:element name="BuildSiteType" type="BuildSiteType" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="Line" type="LineType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="AddtionalUsageType">
		<xsd:sequence>
			<xsd:element name="Line" type="LineType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="LineType">
		<xsd:sequence>
			<xsd:element name="LineRemoveType" type="LineRemoveType" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="LineAddType" type="LineAddType" minOccurs="0" maxOccurs="1"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="LineRemoveType">
		<xsd:sequence>
			<xsd:element name="ProcureLinkId" type="xsd:long" minOccurs="1" maxOccurs="1"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="LineAddType">
		<xsd:sequence>
			<xsd:element name="BomLink" type="BomLinkType" maxOccurs="1"/>
			<xsd:element name="ItemToVariantLink" type="ItemToVariantLinkType" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="Part" type="PartType" minOccurs="1" maxOccurs="1"/>
			<xsd:element name="FinancialInfo" type="FinancialInfoType" maxOccurs="1"/>
			<xsd:element name="RequiredShipToArrive" type="xsd:date" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="BomLinkType">
		<xsd:sequence>
			<xsd:element name="ProcureLinkId" type="xsd:long"/>
			<xsd:element name="PartAffiliation" type="xsd:string"/>
			<xsd:element name="PartNumber" type="xsd:string"/>
			<xsd:element name="PartVersion" type="xsd:string"/>
			<xsd:element name="PartModification" type="xsd:string" minOccurs="0"/>
			<xsd:element name="RefAssemblyPartNo" type="xsd:string" minOccurs="0"/>
			<xsd:element name="RefAssemblyPartVersion" type="xsd:string" minOccurs="0"/>
			<xsd:element name="Quantity" type="xsd:int"/>
			<xsd:element name="ProductClassId" type="xsd:string" minOccurs="0"/>
			<xsd:element name="FunctionGroup" type="xsd:string" minOccurs="0"/>
			<xsd:element name="FunctionGroupSuffix" type="xsd:string" minOccurs="0"/>
			<xsd:element name="ProcureComment" type="xsd:string" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="ItemToVariantLinkType">
		<xsd:annotation>
			<xsd:documentation>ItemToVariantLink attributes</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="Id" type="xsd:long"/>
			<xsd:element name="ModularHarness" type="xsd:string" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="PartType">
		<xsd:annotation>
			<xsd:documentation>KOLA Part attributes</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="Name" type="xsd:string"/>
			<xsd:element name="UnitOfMeasure" type="UnitOfMeasureType"/>
			<xsd:element name="DesignResponsible" type="xsd:string" minOccurs="0"/>
			<xsd:element name="FunctionGroup" type="xsd:string" minOccurs="0"/>
			<xsd:element name="ObjectNumber" type="xsd:string" minOccurs="0"/>
			<xsd:element name="Demarcation" type="xsd:string" minOccurs="0"/>
			<xsd:element name="Characteristics" type="xsd:string" minOccurs="0"/>
			<xsd:element name="Alias" type="AliasType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="AliasType">
		<xsd:sequence>
			<xsd:element name="Id" type="xsd:string"/>
			<xsd:element name="Domain" type="xsd:string"/>
		</xsd:sequence>
	</xsd:complexType>
	<!-- End of Complex Types -->
	<xsd:complexType name="SingelDemandHeaderType">
		<xsd:sequence>
			<xsd:element name="ReferenceId" type="xsd:string"/>
			<xsd:element name="BuiIdId" type="xsd:string" minOccurs="0"/>
			<xsd:element name="BuildStartDate" type="xsd:date" minOccurs="0"/>
			<xsd:element name="RequiredShipToArrive" type="xsd:date" minOccurs="0"/>
			<xsd:element name="ReferenceGroup" type="xsd:string" minOccurs="0"/>
			<xsd:element name="OutboundDate" type="xsd:date" minOccurs="0"/>
			<xsd:element name="OutboundLocationId" type="xsd:string" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:simpleType name="RequestType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="SINGLE"/>
			<xsd:enumeration value="MULTIPLE"/>
			<xsd:enumeration value="FOR_STOCK"/>
			<xsd:enumeration value="ADDITIONAL_USAGE"/>
			<xsd:enumeration value="TESTOBJECT"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="UnitOfMeasureType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="PCE"/>
			<xsd:enumeration value="MMT"/>
			<xsd:enumeration value="GRM"/>
			<xsd:enumeration value="CM2"/>
			<xsd:enumeration value="ML"/>
			<xsd:enumeration value="MTR"/>
			<xsd:enumeration value="KGM"/>
			<xsd:enumeration value="MTK"/>
			<xsd:enumeration value="MTQ"/>
			<xsd:enumeration value="DMQ"/>
			<xsd:enumeration value="FOT"/>
			<xsd:enumeration value="INH"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== perlovdinger/gloria1/Gloria/GloriaUtil/src/main/resources/xsd/materialrequest/4_protomPartAlias/ProtomAliasSmallFA.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ProcessMaterialProcureRequest serviceVersion="String" serviceID="String" xsi:schemaLocation="http://www.volvo.com/MaterialProcureRequest/1_0 MaterialProcureRequest.xsd" xmlns="http://www.volvo.com/MaterialProcureRequest/1_0" xmlns:volvo="http://www.volvo.com/CMF/common/1_0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<volvo:ApplicationArea>
		<volvo:Sender>
			<volvo:LogicalID>PROTOM</volvo:LogicalID>
			<volvo:ComponentID>Subsystem</volvo:ComponentID>
			<volvo:UserID>a026548</volvo:UserID>
		</volvo:Sender>
		<volvo:Receiver>
			<volvo:LogicalID>String</volvo:LogicalID>
			<volvo:ComponentID>text</volvo:ComponentID>
		</volvo:Receiver>
		<volvo:CreationDateTime>2014-11-11T09:30:47Z</volvo:CreationDateTime>
		<volvo:BODID>fcc9f7bc-76a8-469d-a63a-12985e53f23d</volvo:BODID>
	</volvo:ApplicationArea>
	<DataArea>
		<Process/>
		<MaterialRequestChange>
			<RequestType>TESTOBJECT</RequestType>
			<MaterialRequestChangeAdd>
				<Id>Gloria FA</Id>
				<Type>FIRST_ASSEMBLY</Type>
				<ChangeTechId>1556</ChangeTechId>
				<ProcureMessageId>53392</ProcureMessageId>
				<Title/>
				<MaterialRequestMessage>
					<Header>
						<TestObjectHeader>
							<TestObjectInfo>
								<TestObject>
									<Id>Comp-5013</Id>
									<Type>V</Type>
								</TestObject>
							</TestObjectInfo>
							<PhaseInfo>
								<Phase>
									<Id>5936</Id>
									<Name>Gloria FA</Name>
									<Type>FIRST_ASSEMBLY</Type>
									<PlannedAssemblyStartDate>2015-11-30+01:00</PlannedAssemblyStartDate>
								</Phase>
							</PhaseInfo>
						</TestObjectHeader>
						<Requester>
							<UserId>V075869</UserId>
							<Name>Anki Jansson</Name>
							<Notes/>
						</Requester>
						<ContactPerson>
							<UserId>V075869</UserId>
							<Name>Anki Jansson</Name>
						</ContactPerson>
					</Header>
					<Component>
						<BuildSiteType>
							<Id>31967</Id>
						</BuildSiteType>
						<Line>
							<LineAddType>
								<BomLink>
									<ProcureLinkId>12257787485813866</ProcureLinkId>
									<PartAffiliation>V</PartAffiliation>
									<PartNumber>990232</PartNumber>
									<PartVersion>P03</PartVersion>
									<Quantity>5</Quantity>
									<ProductClassId>24</ProductClassId>
									<FunctionGroup>2181</FunctionGroup>
									<FunctionGroupSuffix>01</FunctionGroupSuffix>
									<ProcureComment>ProcureComment1</ProcureComment>
								</BomLink>
								<ItemToVariantLink>
									<Id>8544</Id>
								</ItemToVariantLink>
								<Part>
									<Name>FLANGE SCREW</Name>
									<UnitOfMeasure>PCE</UnitOfMeasure>
									<DesignResponsible>CORSTD</DesignResponsible>
									<Demarcation>M16*200</Demarcation>
									<Characteristics>16*2.00*200 10-9 Y1000SIL</Characteristics>
									<Alias>
										<Id>11-2581124</Id>
										<Domain>NDM</Domain>
									</Alias>
									<Alias>
										<Id>7421810096</Id>
										<Domain>RVI</Domain>
									</Alias>
								</Part>
								<FinancialInfo>
									<ProjectId>M22-P420</ProjectId>
									<CompanyCode>FR46</CompanyCode>
									<GlAccount>461003</GlAccount>
									<CostCenter>0000000011</CostCenter>
									<WbsCode>FLG10-00019</WbsCode>
								</FinancialInfo>
								<RequiredShipToArrive>2015-09-30+02:00</RequiredShipToArrive>
							</LineAddType>
						</Line>
					</Component>
				</MaterialRequestMessage>
			</MaterialRequestChangeAdd>
		</MaterialRequestChange>
	</DataArea>
</ProcessMaterialProcureRequest>
