=== perlovdinger/gloria1/Gloria/GloriaUtil/src/main/resources/xsd/costcenter/1FC_Messages/CostCenter_1_0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2010 (http://www.altova.com) by ï»¿VOLVO INFORMATION TECH AB (VOLVO INFORMATION TECH AB) -->
<xsd:schema xmlns="http://finance.group.volvo.com/costcenter/1_0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cmn="http://finance.group.volvo.com/common/1_0" xmlns:ns1="http://finance.group.volvo.com/costcenter/1_0" targetNamespace="http://finance.group.volvo.com/costcenter/1_0" version="1.0.0">
	<xsd:import namespace="http://finance.group.volvo.com/common/1_0" schemaLocation="../Common_1_0/Common_1_0.xsd"/>
	<xsd:element name="SyncCostCenter">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="Sync" type="cmn:SyncType"/>
				<xsd:element name="CostCenter" type="CostCenterType" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:complexType name="CostCenterType">
		<xsd:annotation>
			<xsd:documentation xml:lang="EN">Cost Center</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="BusinessObjectData" type="cmn:NounHeaderType"/>
			<xsd:element name="CostCenterItem">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="CostCenter" type="cmn:CostCenterType"/>
						<xsd:element name="ControllingArea" type="cmn:ControllingAreaType"/>
						<xsd:element name="BusinessAreaShort" type="cmn:BusinessAreaType"/>
						<xsd:element name="CostCenterDescription" maxOccurs="unbounded">
							<xsd:complexType>
								<xsd:sequence>
									<xsd:element name="ShortText" minOccurs="0">
										<xsd:simpleType>
											<xsd:restriction base="xsd:string">
												<xsd:maxLength value="20"/>
											</xsd:restriction>
										</xsd:simpleType>
									</xsd:element>
									<xsd:element name="LongText" minOccurs="0">
										<xsd:simpleType>
											<xsd:restriction base="xsd:string">
												<xsd:maxLength value="40"/>
											</xsd:restriction>
										</xsd:simpleType>
									</xsd:element>
								</xsd:sequence>
								<xsd:attribute name="language" use="required">
									<xsd:annotation>
										<xsd:documentation>ISO language code, e.g. en, sv, fr</xsd:documentation>
									</xsd:annotation>
								</xsd:attribute>
								<xsd:attribute name="defaultIndicator" type="xsd:boolean">
									<xsd:annotation>
										<xsd:documentation>Indicates if this is the default language for this profit center. If omitted it shall be treated as the same as false.</xsd:documentation>
									</xsd:annotation>
								</xsd:attribute>
							</xsd:complexType>
						</xsd:element>
						<xsd:element name="EffectiveDatePeriod" type="cmn:EffectiveDatePeriodType"/>
						<xsd:element name="CompanyCode" type="cmn:CompanyCodeType"/>
						<xsd:element name="BusinessArea" type="cmn:BusinessAreaType" minOccurs="0"/>
						<xsd:element name="CostCenterCategory" minOccurs="0">
							<xsd:simpleType>
								<xsd:restriction base="xsd:string">
									<xsd:maxLength value="1"/>
								</xsd:restriction>
							</xsd:simpleType>
						</xsd:element>
						<xsd:element name="LogicalSystem" minOccurs="0">
							<xsd:simpleType>
								<xsd:restriction base="xsd:string">
									<xsd:maxLength value="10"/>
								</xsd:restriction>
							</xsd:simpleType>
						</xsd:element>
						<xsd:element name="FunctionalArea" type="cmn:FunctionalAreaType" minOccurs="0"/>
						<xsd:element name="Department" minOccurs="0">
							<xsd:simpleType>
								<xsd:restriction base="xsd:string">
									<xsd:maxLength value="12"/>
								</xsd:restriction>
							</xsd:simpleType>
						</xsd:element>
						<xsd:element name="CurrencyCode" type="cmn:CurrencyCodeType" minOccurs="0"/>
						<xsd:element name="ProfitCenter" type="cmn:ProfitCenterType" minOccurs="0"/>
						<xsd:element name="StandardHierarchyNode" minOccurs="0">
							<xsd:simpleType>
								<xsd:restriction base="xsd:string">
									<xsd:maxLength value="12"/>
								</xsd:restriction>
							</xsd:simpleType>
						</xsd:element>
						<xsd:element name="Segment" minOccurs="0">
							<xsd:simpleType>
								<xsd:restriction base="xsd:string">
									<xsd:maxLength value="10"/>
								</xsd:restriction>
							</xsd:simpleType>
						</xsd:element>
						<xsd:element name="LockIndicators" minOccurs="0">
							<xsd:complexType>
								<xsd:sequence>
									<xsd:element name="PrimaryPostings" type="xsd:boolean"/>
									<xsd:element name="Planning" type="xsd:boolean"/>
									<xsd:element name="ActualSecondaryCosts" type="xsd:boolean"/>
									<xsd:element name="ActualRevenuePostings" type="xsd:boolean"/>
									<xsd:element name="CommitmentUpdate" type="xsd:boolean"/>
									<xsd:element name="PlanSecondaryCosts" type="xsd:boolean"/>
									<xsd:element name="PlanningRevenues" type="xsd:boolean"/>
								</xsd:sequence>
							</xsd:complexType>
						</xsd:element>
						<xsd:element name="PersonResponsibleName" minOccurs="0">
							<xsd:simpleType>
								<xsd:restriction base="xsd:string">
									<xsd:maxLength value="20"/>
								</xsd:restriction>
							</xsd:simpleType>
						</xsd:element>
						<xsd:element name="PersonResponsibleUserId" minOccurs="0">
							<xsd:simpleType>
								<xsd:restriction base="xsd:string">
									<xsd:maxLength value="12"/>
								</xsd:restriction>
							</xsd:simpleType>
						</xsd:element>
						<xsd:element name="Place" minOccurs="0">
							<xsd:simpleType>
								<xsd:restriction base="cmn:PlaceType"/>
							</xsd:simpleType>
						</xsd:element>
						<xsd:element name="Market" type="cmn:MarketType" minOccurs="0"/>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>

=== perlovdinger/gloria1/Gloria/CommonDomain/src/test/resources/globaldataTest/SyncCostCenter_Updates.xml
<?xml version="1.0" encoding="UTF-8"?>
<n1:SyncCostCenter xmlns:n1="http://finance.group.volvo.com/costcenter/1_0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://finance.group.volvo.com/costcenter/1_0 ../CostCenter_1_0.xsd">
  <Sync ReasonCode="Updates">
    <MessageHeader>
      <MsgVersion>1.0.0</MsgVersion>
      <Sender>
        <LogicalId>VGMF</LogicalId>
        <ComponentId>FIMCLNT100</ComponentId>
      </Sender>
      <CreationDateTime>2012-12-11T05:16:56Z</CreationDateTime>
    </MessageHeader>
  </Sync>
  <CostCenter>
    <BusinessObjectData>
      <Action>Create</Action>
    </BusinessObjectData>
    <CostCenterItem>
      <CostCenter>88888888</CostCenter>
      <ControllingArea>Z001</ControllingArea>
      <BusinessAreaShort>BC</BusinessAreaShort>
      <CostCenterDescription language="EN" defaultIndicator="true">
        <ShortText>Roadcrew General</ShortText>
        <LongText>Roadcrew General &amp; Administration</LongText>
      </CostCenterDescription>
      <EffectiveDatePeriod>
        <StartDate>2012-01-01</StartDate>
        <EndDate>9999-12-31</EndDate>
      </EffectiveDatePeriod>
      <CompanyCode>BR03</CompanyCode>
      <CostCenterCategory>Z</CostCenterCategory>
      <FunctionalArea>6020</FunctionalArea>
      <CurrencyCode>GBP</CurrencyCode>
      <ProfitCenter>0000010006</ProfitCenter>
      <StandardHierarchyNode>BC37435</StandardHierarchyNode>
      <PersonResponsibleName>Trevor Smith</PersonResponsibleName>
      <Place>GBWWK01</Place>
      <Market>GB</Market>
    </CostCenterItem>
  </CostCenter>
  <CostCenter>
    <BusinessObjectData>
      <Action>Create</Action>
    </BusinessObjectData>
    <CostCenterItem>
      <CostCenter>99999999</CostCenter>
      <ControllingArea>Z001</ControllingArea>
      <BusinessAreaShort>BC</BusinessAreaShort>
      <CostCenterDescription language="EN" defaultIndicator="true">
        <ShortText>Customer Solutions</ShortText>
        <LongText>Customer Solutions</LongText>
      </CostCenterDescription>
      <EffectiveDatePeriod>
        <StartDate>2012-01-01</StartDate>
        <EndDate>9999-12-31</EndDate>
      </EffectiveDatePeriod>
      <CompanyCode>BR03</CompanyCode>
      <CostCenterCategory>Z</CostCenterCategory>
      <FunctionalArea>7010</FunctionalArea>
      <CurrencyCode>GBP</CurrencyCode>
      <ProfitCenter>0000010051</ProfitCenter>
      <StandardHierarchyNode>BC24160</StandardHierarchyNode>
      <PersonResponsibleName>Paul Martin</PersonResponsibleName>
      <Place>GBRUG01</Place>
      <Market>GB</Market>
    </CostCenterItem>
  </CostCenter>
  <CostCenter>
    <BusinessObjectData>
      <Action>Update</Action>
    </BusinessObjectData>
    <CostCenterItem>
      <CostCenter>1230001110</CostCenter>
      <ControllingArea>Z001</ControllingArea>
      <BusinessAreaShort>BC</BusinessAreaShort>
      <CostCenterDescription language="EN" defaultIndicator="true">
        <ShortText>Updated_Short</ShortText>
        <LongText>Updated_Long</LongText>
      </CostCenterDescription>
      <EffectiveDatePeriod>
        <StartDate>2015-01-15</StartDate>
        <EndDate>2020-12-31</EndDate>
      </EffectiveDatePeriod>
      <CompanyCode>BR03</CompanyCode>
      <CostCenterCategory>Z</CostCenterCategory>
      <FunctionalArea>6010</FunctionalArea>
      <CurrencyCode>GBP</CurrencyCode>
      <ProfitCenter>0000010050</ProfitCenter>
      <StandardHierarchyNode>BC14401</StandardHierarchyNode>
      <PersonResponsibleName>Other, Simon</PersonResponsibleName>
      <PersonResponsibleUserId>someId</PersonResponsibleUserId>
      <Place>GBWWK01</Place>
      <Market>GB</Market>
    </CostCenterItem>
  </CostCenter>
  <CostCenter>
    <BusinessObjectData>
      <Action>Update</Action>
    </BusinessObjectData>
    <CostCenterItem>
      <CostCenter>1230006110</CostCenter>
      <ControllingArea>Z001</ControllingArea>
      <BusinessAreaShort>BC</BusinessAreaShort>
      <CostCenterDescription language="EN" defaultIndicator="true">
        <ShortText>Dlr Bus. Directors</ShortText>
        <LongText>Dealer Business Directors</LongText>
      </CostCenterDescription>
      <EffectiveDatePeriod>
        <StartDate>2015-01-01</StartDate>
        <EndDate>2020-12-31</EndDate>
      </EffectiveDatePeriod>
      <CompanyCode>BR03</CompanyCode>
      <CostCenterCategory>Z</CostCenterCategory>
      <FunctionalArea>6010</FunctionalArea>
      <CurrencyCode>GBP</CurrencyCode>
      <ProfitCenter>0000010001</ProfitCenter>
      <StandardHierarchyNode>BC37409</StandardHierarchyNode>
      <PersonResponsibleName>Joe Roddy</PersonResponsibleName>
      <Place>GBWWK01</Place>
      <Market>GB</Market>
    </CostCenterItem>
  </CostCenter>
  <CostCenter>
    <BusinessObjectData>
      <Action>Delete</Action>
    </BusinessObjectData>
    <CostCenterItem>
      <CostCenter>1230000905</CostCenter>
      <ControllingArea>Z001</ControllingArea>
      <BusinessAreaShort>BC</BusinessAreaShort>
      <CostCenterDescription language="EN" defaultIndicator="true">
        <ShortText>Customer Solutions</ShortText>
        <LongText>Customer Solutions</LongText>
      </CostCenterDescription>
      <EffectiveDatePeriod>
        <StartDate>2012-01-01</StartDate>
        <EndDate>9999-12-31</EndDate>
      </EffectiveDatePeriod>
      <CompanyCode>BR03</CompanyCode>
      <CostCenterCategory>Z</CostCenterCategory>
      <FunctionalArea>7010</FunctionalArea>
      <CurrencyCode>GBP</CurrencyCode>
      <ProfitCenter>0000010051</ProfitCenter>
      <StandardHierarchyNode>BC24160</StandardHierarchyNode>
      <PersonResponsibleName>Paul Martin</PersonResponsibleName>
      <Place>GBRUG01</Place>
      <Market>GB</Market>
    </CostCenterItem>
  </CostCenter>
</n1:SyncCostCenter>
